### ISSUE TITLE
port shelby cge

### ISSUE THREAD

**Issue by diegoac2** [IN-CORE/pyincore#102]
Port Shelby CGE code provided by Tao Lu

**Comment by longshuicy** [comment]
code recieved but running failed with my exiting ipopt and environment
LSEQ1(H)
Traceback (most recent call last):
  File "/Users/cwang138/Documents/INCORE-2.0/PY_shelby/shelby_CES_September_21_2020.py", line 2074, in <module>
    run_solver(filename, tmp)
  File "/Users/cwang138/Documents/INCORE-2.0/PY_shelby/shelby_CES_September_21_2020.py", line 1995, in run_solver
    set_equation(cons_filename)
  File "/Users/cwang138/Documents/INCORE-2.0/PY_shelby/shelby_CES_September_21_2020.py", line 1687, in set_equation
    print(LSEQ1.test(vars.initialVals))
  File "/Users/cwang138/Documents/INCORE-2.0/PY_shelby/shelby/Equationlib.py", line 830, in test
    print(i,j,fun(x))
  File "/Users/cwang138/Documents/INCORE-2.0/PY_shelby/shelby/Equationlib.py", line 829, in <lambda>
    fun = lambda x: eval( self.m[i][j].debug_test_str() )
RecursionError: maximum recursion depth exceeded during compilation

But conda environment provided and I will try installing that and see how it goes.

**Comment by longshuicy** [comment]
code works after increase the recursion limit 
```
import sys
sys.setrecursionlimit(10000)
```
