### ISSUE TITLE
Mean damage handle empty row breaks when connecting with non-structure damage

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/pyincore#390]
To reproduce run `mean_dmg.ipynb` notebook

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/opt/conda/lib/python3.9/site-packages/pyincore/analyses/meandamage/meandamage.py", line 171, in mean_damage_bulk_input
    self.mean_damage(dmg, dmg_ratio_tbl, damage_interval_keys,
  File "/opt/conda/lib/python3.9/site-packages/pyincore/analyses/meandamage/meandamage.py", line 212, in mean_damage
    mean_damage = AnalysisUtil.calculate_mean_damage(dmg_ratio_tbl,
  File "/opt/conda/lib/python3.9/site-packages/pyincore/utils/analysisutil.py", line 107, in calculate_mean_damage
    float_dmg_intervals = AnalysisUtil.dmg_string_dict_to_dmg_float_dict(dmg_intervals)
  File "/opt/conda/lib/python3.9/site-packages/pyincore/utils/analysisutil.py", line 92, in dmg_string_dict_to_dmg_float_dict
    float_dmg_dict[key] = float(dmg_dict[key])
ValueError: could not convert string to float: 'yes'
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2392/3551814197.py in <module>
      5 md.set_parameter("damage_interval_keys", ["DS_DS_0", "DS_DS_1", "DS_DS_2", "DS_DS_3"])
      6 md.set_parameter("num_cpu", 1)
----> 7 md.run_analysis()

/opt/conda/lib/python3.9/site-packages/pyincore/baseanalysis.py in run_analysis(self)
    291                 return result
    292 
--> 293         return self.run()
    294 
    295     def run(self):

/opt/conda/lib/python3.9/site-packages/pyincore/analyses/meandamage/meandamage.py in run(self)
    119             count += avg_bulk_input_size
    120 
--> 121         results = self.mean_damage_concurrent_future(
    122             self.mean_damage_bulk_input, num_workers,
    123             inventory_args, repeat(dmg_ratio_tbl))

/opt/conda/lib/python3.9/site-packages/pyincore/analyses/meandamage/meandamage.py in mean_damage_concurrent_future(self, function_name, parallelism, *args)
    141         with concurrent.futures.ProcessPoolExecutor(
    142                 max_workers=parallelism) as executor:
--> 143             for ret in executor.map(function_name, *args):
    144                 output.extend(ret)
    145 

/opt/conda/lib/python3.9/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    557     careful not to keep references to yielded objects.
    558     """
--> 559     for element in iterable:
    560         element.reverse()
    561         while element:

/opt/conda/lib/python3.9/concurrent/futures/_base.py in result_iterator()
    606                     # Careful not to keep a reference to the popped future
    607                     if timeout is None:
--> 608                         yield fs.pop().result()
    609                     else:
    610                         yield fs.pop().result(end_time - time.monotonic())

/opt/conda/lib/python3.9/concurrent/futures/_base.py in result(self, timeout)
    443                     raise CancelledError()
    444                 elif self._state == FINISHED:
--> 445                     return self.__get_result()
    446                 else:
    447                     raise TimeoutError()

/opt/conda/lib/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

ValueError: could not convert string to float: 'yes'
```

non structure damage has more content

**Comment by navarroc** [comment]
Fixed by #393
